# Generated by Django 5.0 on 2026-03-13 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PadronCasas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_casa', models.CharField(max_length=20, unique=True)),
                ('ocupada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Casa',
                'verbose_name_plural': 'Padrón de Casas',
                'db_table': 'padron_casas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('casa', models.OneToOneField(db_column='numero_casa', on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to='auth_app.padroncasas', to_field='numero_casa')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='TokenRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacion', to='auth_app.usuario')),
            ],
            options={
                'verbose_name': 'Token de Recuperación',
                'verbose_name_plural': 'Tokens de Recuperación',
                'db_table': 'tokens_recuperacion',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='auth_app.usuario')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'db_table': 'sesiones',
            },
        ),
    ]

